---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLCluster
    singular: mysqlcluster
    plural: mysqlclusters
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: mysql-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mysql-operator
  namespace: mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: mysql-operator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      imagePullSecrets:
        - name: odx-docker-pull-secret
      containers:
      - name: mysql-operator-controller
        imagePullPolicy: Always
        image: registry.oracledx.com/skeppare/mysql-operator:0.1.0
        ports:
        - containerPort: 10254
        args:
          - --v=4
