kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weblogic-operator-claim
spec:
  storageClassName: weblogic-operator
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi