---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weblogic-operator
  namespace: weblogic-operator
  labels:
    app: weblogic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic-operator
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
      serviceAccountName: weblogic-operator
      containers:
      - name: weblogic-operator-controller
        imagePullPolicy: Always
        image: fmwplt/weblogic-operator:{{VERSION}}
        ports:
        - containerPort: 9999
        args:
          - --v=4
          - --alsologtostderr=true
