---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weblogicservers.weblogic.oracle.com
spec:
  group: weblogic.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: WeblogicServer
    singular: weblogicserver
    plural: weblogicservers
---