---
#apiVersion: "weblogic.oracle.com/v1"
#kind: WebLogicDomain
#metadata:
#  name: basedomain
#  spec:
#    version: 12.2.1.2
#    server:
#      metadata:
#        name: managedserver
#        spec:
#          version: 12.2.1.2
#          replicas: 5
---
---
apiVersion: "weblogic.oracle.com/v1"
kind: WebLogicDomain
metadata:
  name: firstdomain
spec:
  version: 12.2.1.2
  managedServerCount: 3
---
---
apiVersion: "weblogic.oracle.com/v1"
kind: WebLogicDomain
metadata:
  name: seconddomain
spec:
  version: 12.2.1.2
  managedServerCount: 2
---
