---
apiVersion: "weblogic.oracle.com/v1"
kind: WebLogicManagedServer
metadata:
  name: adminserver
---
apiVersion: "weblogic.oracle.com/v1"
kind: WebLogicManagedServer
metadata:
  name: managedserver
spec:
  version: 12.2.1.2
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
---