apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 13306
    name: mysql-replication
  clusterIP: None
  selector:
    app: mysql
